# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python CI with Poetry

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
    - name: Test with pytest
      run: |
        poetry run pytest --junitxml=relatorio_testes.xml
    - name: Build with poetry
      run: |
        poetry build
    - name: Upload do Relatório de Testes
      run: |
        with:
          name: relatorio-de-testes-${{ github.sha }}
          path: relatorio_testes.xml
          if-no-files-found: error
    - name: Upload do Pacote Buildado
      run: |
        with:
          name: pacote-buildado
          path: dist/
          if-no-files-found: error
    - name: Enviar Notificação de Pipeline
      if: always()
      uses: dawidd6/action-send-mail@v3
        with: 
          server_address: smtp.hotmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
      
         
          to: ${{ vars.EMAIL }}
      
        
          subject: '[CI/CD Pipeline] Status do Projeto: ${{ github.repository }}'
          body: |
            Pipeline executado!
      
            --------------------------------
            STATUS GERAL: ${{ job.status }} 
            --------------------------------
